spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true